name: kanada
description: "Kanada"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  kanada_album_art:
    path: ./kanada_album_art
  kanada_lyric_sender:
    path: ./kanada_lyric_sender
  kanada_volume:
    path: ./kanada_volume
#  kanada_lyric_server:
#    path: ./kanada_lyric_server
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  audio_service: ^0.18.18
  just_audio: ^0.9.46
  just_audio_background:
    path: ./just_audio_background
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.12
  audio_metadata_reader: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  path: ^1.9.1

publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true   # 为 Android 生成图标
  ios: false       # 为 iOS 生成图标
  image_path: "assets/icon/Kanade.png"  # 图标源文件路径
  # 可选参数（按需配置）：
  adaptive_icon_background: "#FFFFFF"  # Android 自适应图标背景色
  adaptive_icon_foreground: "assets/icon/Kanade.png"  # 前景图层